pipeline {
    agent any

    triggers {
        cron('H 0 * * *')
    }

    environment {
        MAVEN_HOME = tool(name: 'Maven 3.6.3')
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/DmytroMarkulych/cursova.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Tests failed!'
        }
        success {
            echo 'Tests succeeded!'
        }
    }
}
